### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by rbairwell** [silktide/syringe#40]
It doesn't seem possible to escape things such as:
```
parameters:
  atuinclient.atuinPathTemplate: "https://api.atuin.silktide.com/service/%SERVICENAME%"
```
results in:
```
Silktide\Syringe\Exception\ReferenceException: Error with key 'atuinclient.atuinPathTemplate'. Tried to inject the parameter 'SERVICENAME' in an argument list, but it doesn't exist
```
(as % is in indicator for expansion). Doubling up the % or escaping them with backslashes doesn't work (latter results in `` Could not load the YAML file '/...syringe.yml': Found unknown escape character "\%" at line 2``, doubling the backslashes returns to the original error).

**Comment by Dolondro** [comment]
This is fixed in v2 with the syntax of `%%SERVICENAME%%` in the example given
