### ISSUE TITLE
Allow constants to be injected

### ISSUE THREAD

**Issue by downsider** [silktide/syringe#9]
This is a proposal to allow PHP constants to be used in Syringe configuration.

Where a method argument is an enumerated value, it is often the case that a PHP constant will be used to represent the value so that if that value needs to change for some reason, no code other than the constant definition is required to change.

Currently, if such an argument is used in a service constructer or method call, the raw value must be specified. This means there is more than one place where the value of the constant is present, removing a lot of the usefulness of the constant.

We could define another character (perhaps ^, but other ideas are welcome) to represent constants that are to be injected into a service. Use of PHPs class constant syntax would be acceptable and I would envisage that parameters could be used within this to allow for the following:

    parameters:
        namespace: "Silktide\\Syringe"
    
    services:
        test:
            class: ...
            arguments:
                - "^%namespace%\\Type::STRING"
                - "^%namespace%\\Reason::WHY"

**Comment by Dolondro** [comment]
It's worth noting that we would want to support non-class based constants as well.

A good example would be being able to allow a Monolog StreamHandler access to the STDOUT constant.

I find no issue with the syntax suggested.

**Comment by Dolondro** [comment]
Patch made which supports suggested functionality #17

**Comment by downsider** [comment]
PR #17 merged and released in 1.1.6
